//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGames.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN
    {
        public int Id { get; set; }
        public string dn_id { get; set; }
        public System.Guid mt_id { get; set; }
        public string msisdn { get; set; }
        public Nullable<int> shortcode { get; set; }
        public string keyword { get; set; }
        public string dnType { get; set; }
        public string status { get; set; }
        public string statusCode { get; set; }
        public string statusMsg { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
    
        public virtual MT MT { get; set; }
    }
}
