//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGames.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingClick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LandingClick()
        {
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public System.Guid Id { get; set; }
        public string Txid { get; set; }
        public string Affid { get; set; }
        public string PubId { get; set; }
        public System.DateTime LandingDate { get; set; }
        public string LandingSource { get; set; }
        public Nullable<System.DateTime> FirebackDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
