//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGames.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MO
    {
        public System.Guid mo_id { get; set; }
        public string txid { get; set; }
        public string msisdn { get; set; }
        public Nullable<int> shortcode { get; set; }
        public string keyword { get; set; }
        public string message { get; set; }
        public string action { get; set; }
        public string mo_origin { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
    }
}
