//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGames.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KSAPlatGamesMobimindEntities : DbContext
    {
        public KSAPlatGamesMobimindEntities()
            : base("name=KSAPlatGamesMobimindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailySubInfo> DailySubInfoes { get; set; }
        public virtual DbSet<DN> DNs { get; set; }
        public virtual DbSet<Landing> Landings { get; set; }
        public virtual DbSet<LandingClick> LandingClicks { get; set; }
        public virtual DbSet<MO> MOes { get; set; }
        public virtual DbSet<MT> MTs { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionHistory> SubscriptionHistories { get; set; }
        public virtual DbSet<TelcoInfo> TelcoInfoes { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionSummary> TransactionSummaries { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
    
        [DbFunction("KSAPlatGamesMobimindEntities", "GetRevenueReport")]
        public virtual IQueryable<GetRevenueReport_Result> GetRevenueReport(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRevenueReport_Result>("[KSAPlatGamesMobimindEntities].[GetRevenueReport](@From, @To)", fromParameter, toParameter);
        }
    
        [DbFunction("KSAPlatGamesMobimindEntities", "SubscriptionInfo")]
        public virtual IQueryable<SubscriptionInfo_Result> SubscriptionInfo(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SubscriptionInfo_Result>("[KSAPlatGamesMobimindEntities].[SubscriptionInfo](@From, @To)", fromParameter, toParameter);
        }
    
        [DbFunction("KSAPlatGamesMobimindEntities", "TransactionSummaryReport")]
        public virtual IQueryable<TransactionSummaryReport_Result> TransactionSummaryReport(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TransactionSummaryReport_Result>("[KSAPlatGamesMobimindEntities].[TransactionSummaryReport](@From, @To)", fromParameter, toParameter);
        }
    
        public virtual int AddLanding()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLanding");
        }
    }
}
