//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGames.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid Id { get; set; }
        public int TypeID { get; set; }
        public System.Guid SubscriptionId { get; set; }
        public System.DateTime Date { get; set; }
        public int TelcoId { get; set; }
        public string RequestID { get; set; }
        public string Msisdn { get; set; }
        public decimal Price { get; set; }
        public int OperatorID { get; set; }
        public int ChannelID { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual TelcoInfo TelcoInfo { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
