//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySubInfo
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string telcoName { get; set; }
        public int totalCanceled { get; set; }
        public int totalRegistered { get; set; }
        public int totalRenewal { get; set; }
        public int totalActive { get; set; }
        public string shortcode { get; set; }
        public string keyword { get; set; }
        public decimal dailyCampaignSubRevenue { get; set; }
        public decimal dailyCampaignRenRevenue { get; set; }
        public decimal dailyCampaignRevenue { get; set; }
        public decimal dailyPortalSubRevenue { get; set; }
        public decimal dailyPortalRenRevenue { get; set; }
        public decimal dailyPortalRevenue { get; set; }
        public decimal dailySubRevenue { get; set; }
        public decimal dailyRenRevenue { get; set; }
        public decimal dailyRevenue { get; set; }
        public int totalInActive { get; set; }
    }
}
