//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid SubscriptionId { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string SubMethod { get; set; }
        public string TerminationMethod { get; set; }
        public string SubscribedBy { get; set; }
        public string TerminatedBy { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<bool> RenewalSent { get; set; }
        public bool IsSubscribed { get; set; }
        public int TelcoId { get; set; }
        public string Msisdn { get; set; }
        public string Txid { get; set; }
        public Nullable<System.DateTime> LastCharegDate { get; set; }
        public Nullable<bool> IsCampaign { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> LandingClicksId { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual TelcoInfo TelcoInfo { get; set; }
    }
}
