//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionSummary
    {
        public int ID { get; set; }
        public string TelcoId { get; set; }
        public System.DateTime Date { get; set; }
        public int UniqueMSISDNCampaign { get; set; }
        public int CampaignOptIn { get; set; }
        public double CampaignOptInPercentage { get; set; }
        public int UniqueMSISDNPortal { get; set; }
        public int PortalOptIn { get; set; }
        public int TotalActiveSubscribers { get; set; }
        public int DailyCampaignOptOut { get; set; }
        public int TotalCampaignOptOut { get; set; }
        public int DailyPortalOptOut { get; set; }
        public int TotalPortalOptOut { get; set; }
        public int TotalInactiveSubscribers { get; set; }
        public int Renewal { get; set; }
        public int Revenue { get; set; }
        public int RenewalCampaign { get; set; }
        public int RenewalPortal { get; set; }
    }
}
